name: csd2
channels:
    - conda-forge

dependencies:
   - python=3.9
   - pip
   - compas=1.17.4
   - scipy=1.10.1
   - compas_cgal=0.5.0
   - pip:
     - compas_cloud==0.4.1
     - compas_ui==0.9.1
     - compas_tna==0.2.0
     - compas_rv3==0.4.0
